/* THIS IS AN AUTOGENERATED FILE, PLEASE EDIT service_list.yaml */
#ifndef __SERVICES_H
#define __SERVICES_H
struct service
{
    char name[0x100];
    int port;
    bool should_log;
    int frequency;
    int decimation;
};
static struct service services[] = {
    {"remote_comm", 5558, true, 20, 1},
    {"remote_comm_ctrl", 5559, true, 20, 1},
};
#endif
